version: "3.9"

services:
  dev_vscode:
    # image: mcr.microsoft.com/vscode/devcontainers/base
    build:
      context: ../
      dockerfile: backend/Dockerfile
      args:
        - VARIANT=1.17
    volumes:
      - ../:/workspace/

    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined

    tty: true
    networks: ['stack']
    depends_on: ['db_mongo']

  # backend: 
  #   image: "mcr.microsoft.com/vscode/devcontainers/go:0-VARIANT=1-bullseye"
  #   networks: ['stack']
  #   depends_on: ['db_mongo']

  #   volumes:
  #     - ../backend:/workspace/backend

  db_mongo:
    image: "mongo:5.0.6"
    networks: ['stack']

networks:
  stack: {}
